java_library(
    name = "artemis-service-extensions",
    srcs = glob(["src/main/java/**/*.java"]),
    visibility = ["//visibility:public"],
    deps = [
        #        "//third_party:org_apache_geronimo_specs_geronimo_j2ee_connector_1_5_spec",
        #        "//third_party:org_apache_geronimo_specs_geronimo_jms_2_0_spec",
        "//third_party:org_apache_geronimo_specs_geronimo_jta_1_1_spec",
        "//artemis-core-client",
        "//third_party:org_jboss_logging_jboss_logging",
        "//third_party/ap:org_jboss_logging_jboss_logging_annotations",
        "//artemis-commons",
        "//artemis-jms-client",
    ],
)
